/// Error handling module for the Airtel Money SDK
///
/// This module provides custom error types to replace the generic
/// `Box<dyn std::error::Error>` pattern and provide better error handling
/// with more specific error information.
use std::fmt;

/// Main error type for Airtel Money SDK operations
///
/// This enum covers all possible error scenarios that can occur
/// when using the Airtel Money API, providing better error handling
/// and debugging information.
///
/// # Examples
///
/// ```rust
/// use airtel_rs::AirtelError;
///
/// match some_api_call().await {
///     Ok(response) => println!("Success: {:?}", response),
///     Err(AirtelError::AuthenticationError { message }) => {
///         eprintln!("Authentication failed: {}", message);
///     }
///     Err(AirtelError::ApiError { status, message }) => {
///         eprintln!("API error {}: {}", status, message);
///     }
///     Err(e) => eprintln!("Other error: {}", e),
/// }
/// ```
#[derive(thiserror::Error, Debug)]
pub enum AirtelError {
    /// HTTP request/response errors from reqwest
    #[error("HTTP error: {0}")]
    HttpError(#[from] reqwest::Error),

    /// API authentication/authorization errors
    #[error("Authentication error: {message}")]
    AuthenticationError {
        /// Error message from the API
        message: String,
    },

    /// API-specific errors with status codes
    #[error("API error ({status}): {message}")]
    ApiError {
        /// HTTP status code
        status: u16,
        /// Error message from the API
        message: String,
    },

    /// JSON serialization/deserialization errors
    #[error("Serialization error: {0}")]
    SerializationError(#[from] serde_json::Error),

    /// Token-related errors (expired, invalid, etc.)
    #[error("Token error: {message}")]
    TokenError {
        /// Token error description
        message: String,
    },

    /// Network connectivity errors
    #[error("Network error: {message}")]
    NetworkError {
        /// Network error description
        message: String,
    },

    /// Invalid configuration errors
    #[error("Configuration error: {message}")]
    ConfigurationError {
        /// Configuration error description
        message: String,
    },

    /// Validation errors for request parameters
    #[error("Validation error for '{field}': {message}")]
    ValidationError {
        /// Field that failed validation
        field: String,
        /// Validation error message
        message: String,
    },

    /// Rate limit exceeded error
    #[error("Rate limit exceeded. Retry after {retry_after} seconds")]
    RateLimitExceeded {
        /// Number of seconds to wait before retrying
        retry_after: u64,
    },

    /// Circuit breaker open error
    #[error("Circuit breaker is open. Service temporarily unavailable")]
    CircuitBreakerOpen,

    /// Request timeout error
    #[error("Request timed out after {timeout} milliseconds")]
    RequestTimeout {
        /// Timeout duration in milliseconds
        timeout: u64,
    },

    /// Environment variable missing error
    #[error("Missing required environment variable: {variable}")]
    MissingEnvironmentVariable {
        /// Name of the missing environment variable
        variable: String,
    },

    /// Retry failed after maximum attempts
    #[error("Request failed after {attempts} retry attempts")]
    RetryFailed {
        /// Number of attempted retries
        attempts: u32,
    },
}

// Error implementations automatically generated by thiserror

/// Convert reqwest errors to appropriate AirtelError variants
impl From<reqwest::Error> for AirtelError {
    fn from(error: reqwest::Error) -> Self {
        if error.is_timeout() {
            AirtelError::RequestTimeout {
                timeout: error
                    .timeout()
                    .and_then(|d| Some(d.as_millis() as u64))
                    .unwrap_or(0),
            }
        } else if error.is_connect() {
            AirtelError::NetworkError {
                message: error.to_string(),
            }
        } else {
            AirtelError::HttpError(error)
        }
    }
}

/// Result type alias for Airtel Money SDK operations
///
/// This type alias provides a convenient way to return results
/// from SDK operations with the custom error type.
///
/// # Examples
///
/// ```rust
/// use airtel_rs::{AirtelResult, AirtelError};
///
/// async fn some_api_operation() -> AirtelResult<String> {
///     // API operation logic here
///     Ok("Success".to_string())
/// }
/// ```
pub type AirtelResult<T> = Result<T, AirtelError>;

/// Helper function to create an authentication error
///
/// # Arguments
///
/// * `message` - The authentication error message
///
/// # Examples
///
/// ```rust
/// use airtel_rs::errors::auth_error;
///
/// let error = auth_error("Invalid credentials");
/// ```
pub fn auth_error(message: &str) -> AirtelError {
    AirtelError::AuthenticationError {
        message: message.to_string(),
    }
}

/// Helper function to create an API error
///
/// # Arguments
///
/// * `status` - HTTP status code
/// * `message` - Error message
///
/// # Examples
///
/// ```rust
/// use airtel_rs::errors::api_error;
///
/// let error = api_error(400, "Bad Request");
/// ```
pub fn api_error(status: u16, message: &str) -> AirtelError {
    AirtelError::ApiError {
        status,
        message: message.to_string(),
    }
}

/// Helper function to create a validation error
///
/// # Arguments
///
/// * `field` - The field that failed validation
/// * `message` - Validation error message
///
/// # Examples
///
/// ```rust
/// use airtel_rs::errors::validation_error;
///
/// let error = validation_error("phone_number", "Invalid format");
/// ```
#[allow(dead_code)]
pub fn validation_error(field: &str, message: &str) -> AirtelError {
    AirtelError::ValidationError {
        field: field.to_string(),
        message: message.to_string(),
    }
}
